# Generated by extendr: Do not edit by hand
# nolint start

#' @usage NULL
#' @useDynLib rpic, .registration = TRUE
NULL

rpic_svg_ <- function(src, circuits) .Call(wrap__rpic_svg_, src, circuits)

rpic_png_ <- function(src, file, scale, circuits) .Call(wrap__rpic_png_, src, file, scale, circuits)

rpic_pdf_ <- function(src, file, circuits) .Call(wrap__rpic_pdf_, src, file, circuits)

rpic_manifest_ <- function(src, circuits) .Call(wrap__rpic_manifest_, src, circuits)

# nolint end
